Settings:
  Prefix: "&#27ae60☪ &#2ebd68&lMoxCamii &8» &7"

  Namaz-Vakitleri:
    Timezone: "Europe/Istanbul"
    API-URL: "http://api.aladhan.com/v1/timingsByCity?city=Istanbul&country=Turkey&method=13"

  Others:
    Abdest-Timeout: 30
    Door-Pushback-Strength: 1.5
    Reward-Delay-Seconds: 5
    Seat-YOffset: -1.7

  Database:
    Type: "SQLite" # SQLite veya MySQL
    Host: "127.0.0.1"
    Port: 3306
    Database: "moxnetwork"
    Username: "root"
    Password: "password"
    Table-Prefix: "moxcamii_"

  Redis:
    Enabled: true
    Host: "127.0.0.1"
    Port: 6379
    Password: ""
    Cluster-ID: "mox-network"